### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by sevgicorumlu** [kokke/tiny-ECDH-c#17]
/tmp/cc6EXGlG.o: In function `ecdh_demo':
ecdh_example.c:(.text+0x150): undefined reference to `ecdh_generate_keys'
ecdh_example.c:(.text+0x1ad): undefined reference to `ecdh_generate_keys'
ecdh_example.c:(.text+0x1ea): undefined reference to `ecdh_shared_secret'
ecdh_example.c:(.text+0x227): undefined reference to `ecdh_shared_secret'
/tmp/cc6EXGlG.o: In function `ecdsa_broken':
ecdh_example.c:(.text+0x337): undefined reference to `ecdh_generate_keys'
ecdh_example.c:(.text+0x358): undefined reference to `ecdsa_sign'
ecdh_example.c:(.text+0x372): undefined reference to `ecdsa_verify'
collect2: error: ld returned 1 exit status

**Comment by kokke** [comment]
Hi @sevgicorumlu and thanks for posting here :)

From the errors, it seems you are only compiling `ecdh_example.c`.

All the functions missing reside in `ecdh.c`.
You need to also compile + link that file in the build.

This is a common error for less experienced developers. 
See similar issues in my AES project:
https://github.com/kokke/tiny-AES-c/issues/107
https://github.com/kokke/tiny-AES-c/issues/79
https://github.com/kokke/tiny-AES-c/issues/71

Closing since this is a user-error, not including a file in the build.

**Comment by sevgicorumlu** [comment]
Hİ @kokke thank you.
